# markdownlint configuration for BetaNet
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD003/heading-style - Heading style
MD003:
  # Heading style
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2
  start_indented: false

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: false

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: true
  spaces_per_tab: 4

# MD013/line-length - Line length
MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  allow_different_nesting: true
  siblings_only: false

# MD025/single-title/single-h1 - Multiple top level headings in the same document
MD025:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!?"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: "one_or_ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: true

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements: [
    "details", "summary", "br", "sub", "sup", "kbd", "mark",
    "span", "div", "table", "thead", "tbody", "tr", "th", "td"
  ]

# MD034/no-bare-urls - Bare URL used
MD034: true

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036:
  punctuation: ".,;:!?。，；：！？"

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD041/first-line-heading/first-line-h1 - First line in file should be a top level heading
MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD042/no-empty-links - No empty links
MD042: true

# MD043/required-headings - Required heading structure
MD043: false

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  names: [
    "BetaNet", "HTX", "QUIC", "TLS", "HTTP", "HTTPS", "TCP", "UDP",
    "CMake", "OpenSSL", "mbedTLS", "GitHub", "CI", "CD", "API",
    "JSON", "YAML", "XML", "HTML", "CSS", "JavaScript", "TypeScript",
    "Doxygen", "Clang", "GCC", "MSVC", "AddressSanitizer", "UndefinedBehaviorSanitizer",
    "MemorySanitizer", "ThreadSanitizer", "Valgrind", "AFL", "libFuzzer",
    "Kyber768", "X25519", "ChaCha20", "Poly1305", "AES", "GCM",
    "SHA256", "SHA512", "HMAC", "ECDSA", "RSA", "Noise", "XK",
    "SCION", "IPv4", "IPv6", "DNS", "mDNS", "DHT", "PoW",
    "Ubuntu", "Debian", "CentOS", "RHEL", "macOS", "Windows", "Linux",
    "ARM64", "ARMhf", "x86", "x64", "MIPS", "RISC-V"
  ]
  code_blocks: false

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: true

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  style: "asterisk"

# MD050/strong-style - Strong style should be consistent
MD050:
  style: "asterisk"

# MD051/link-fragments - Link fragments should be valid
MD051: true

# MD052/reference-links-images - Reference links and images should use a label that is defined
MD052: true

# MD053/link-image-reference-definitions - Link and image reference definitions should be needed
MD053: true
